"""create db

Revision ID: 638c7604912d
Revises: 
Create Date: 2021-05-22 23:49:23.375600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '638c7604912d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.add_column('building', sa.Column('squre', sa.Float(), nullable=False))
    op.alter_column('building', 'addr_house',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('building', 'floor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('building', 'typehouse',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('building_geom_idx', table_name='building')
    op.drop_column('building', 'square')
    op.alter_column('trees-point', 'chieucao',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trees-point', 'loaicay',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index('trees-point_geom_idx', table_name='trees-point')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('trees-point_geom_idx', 'trees-point', ['geom'], unique=False)
    op.alter_column('trees-point', 'loaicay',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('trees-point', 'chieucao',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('building', sa.Column('square', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('building_geom_idx', 'building', ['geom'], unique=False)
    op.alter_column('building', 'typehouse',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('building', 'floor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('building', 'addr_house',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.drop_column('building', 'squre')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
