"""create db

Revision ID: c8cc96531312
Revises: 
Create Date: 2021-05-25 17:00:29.001652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8cc96531312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.alter_column('building', 'addr_house',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('building', 'floor',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('building', 'square',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('building', 'typehouse',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trees-point', 'chieucao',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trees-point', 'loaicay',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trees-point', 'loaicay',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('trees-point', 'chieucao',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('building', 'typehouse',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('building', 'square',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('building', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('building', 'floor',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('building', 'addr_house',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
